/*
* generated by Xtext
*/
package com.viacron.utils.bbb.ui.contentassist;

import com.viacron.utils.bbb.ui.contentassist.AbstractByteByByteProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ByteByByteProposalProvider extends AbstractByteByByteProposalProvider {

}
