<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="byteByByte"
    nsURI="http://www.viacron.com/utils/bbb/ByteByByte" nsPrefix="byteByByte">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="grammarName" eType="#//GrammarName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//PackageDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootClass" eType="#//RootClass"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dateTimeFormat" eType="#//DateTimeFormat"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1"
        eType="#//SubType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="penums" upperBound="-1"
        eType="#//PEnum" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GrammarName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeFormat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTimeFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//AbstractAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enums" upperBound="-1"
        eType="#//PEnumRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOf" eType="#//ListOF"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optional" eType="#//Optional"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//AbstractAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeType" eType="#//AttributeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttributeType">
    <eLiterals name="STRING" literal="string"/>
    <eLiterals name="BYTE" value="1" literal="byte"/>
    <eLiterals name="CHAR" value="2" literal="char"/>
    <eLiterals name="INT" value="3" literal="integer"/>
    <eLiterals name="FLOAT" value="4" literal="float"/>
    <eLiterals name="DOUBLE" value="5" literal="double"/>
    <eLiterals name="SHORT" value="6" literal="short"/>
    <eLiterals name="LONG" value="7" literal="long"/>
    <eLiterals name="CALENDAR" value="8" literal="calendar"/>
    <eLiterals name="BOOLEAN" value="9" literal="boolean"/>
    <eLiterals name="XREF" value="10" literal="XREF"/>
    <eLiterals name="ID" value="11" literal="ID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListOF">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listOf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Optional">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubTypeRef" eSuperTypes="#//AbstractAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subType" eType="#//SubType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PEnumRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="penum" eType="#//PEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optional" eType="#//Optional"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//AbstractAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enums" upperBound="-1"
        eType="#//PEnumRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PEnum">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//PEnumElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PEnumElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
