/*
 * WARNING: This file was generated by BitByBitGenerator.xtend (see
 * generateInstantiationFile()). 
 * Do not edit.
 */
package com.bbb.example;
import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import com.viacron.utils.StringMessageBuffer.parser.AbstractAttribute;
import com.viacron.utils.StringMessageBuffer.parser.Element;
import com.viacron.utils.StringMessageBuffer.parser.KeyValuePair;

public class InstantiateHelloWorld {
   private static Logger log4j = Logger.getLogger(InstantiateHelloWorld.class);

   /*
    * The isUpdated flags. If an attribute is required by the grammar then a value
    * must be provided, and the isUpdated flag will be set when the value is
    * obtained during unpacking. After the object is constructed during unpacking, 
    * validation will be performed to make sure a value was provided for all attributes
    * that are not optional. 
    * See buildFlags() in JBitByBitGenerator.java.
    */
   private boolean isGreetingUpdated = false;

   private Element element;
   private HelloWorld helloWorld;

   /**
    * The InstantiateHelloWorld class instantiates the HelloWorld object.
    *
    * @param element The root element returned by the parser after parsing the string
    *                representing the HelloWorld.
    */
   public InstantiateHelloWorld(Element element) {
      this.element = element;   
      this.helloWorld = new HelloWorld();
   }

   /**
    * This method instantiates the HelloWorld.
    *
    * @return The HelloWorld.
    */
   public HelloWorld instantiate() {
      final String METHOD = "instantiate()";
      log4j.debug("Entered " + METHOD);

      log4j.debug("HelloWorld: " + element.getName());
      log4j.debug("# of attributes: " + element.getAbstractAttributes().size());

      instantiateHelloWorldAttributes(element);

      for (AbstractAttribute abstractAttribute : element
            .getAbstractAttributes()) {
         for (Element e : abstractAttribute.getElements()) {
            log4j.debug("element name: " + e.getName());
      instantiateHelloWorldSubTypeRefs(e);
      }
      }

      log4j.debug("Leaving " + METHOD);
      return helloWorld;
      }

      /*
       * This method instantiates the HelloWorld attributes.
       * 
       * @param Element element
       */
      private void instantiateHelloWorldAttributes(Element element) {
      final String METHOD = "instantiateHelloWorldAttributes()";
      log4j.debug("Entered " + METHOD);

      log4j.debug("element name: " + element.getName());
      for (AbstractAttribute attr : element.getAbstractAttributes()) {
         for (KeyValuePair kvp : attr.getKeyValuePairs()) {
            log4j.debug("key: " + kvp.getKey());
            log4j.debug("value: " + kvp.getValue());
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("greeting")) {
               log4j.debug("setting value of \"greeting\" to: " + kvp.getValue());
               this.isGreetingUpdated = true;
               helloWorld.setGreeting(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
         }
      }

      log4j.debug("Leaving " + METHOD);
   }

   /*
    * This method instantiates the HelloWorld SubType references.
    * 
    * @param Element element
    */
   private void instantiateHelloWorldSubTypeRefs(Element element) {
      final String METHOD = "instantiateHelloWorldSubTypeRefs()";
      log4j.debug("Entered " + METHOD);


      log4j.debug("Leaving " + METHOD);
   }


   /**
    * The validate method checks that a value was provided for all required 
    * attributes.
    *
    * @return The error message or null if no error occurred.
    */
   protected String validate() {
      final String METHOD = "validate()";
      log4j.debug("Entered " + METHOD);

      String result = null;

      // Entered buildValidationMethod()
      if (!this.isGreetingUpdated) {
         String msg = "Greeting is required, but no value was provided.";
         if (result == null) {
            result = msg;
         }
      }


      if (result != null) {
         log4j.debug("result: " + result);
      }

      log4j.debug("Leaving " + METHOD);
      return result;
   }
}
