/*
 * WARNING: This file was generated by BitByBitGenerator.xtend (see
 * generateClassFile()). 
 * Do not edit.
 */
package com.viacron.greenball.app.bbb;

import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.log4j.Logger;
/**
 * The Include class is a SubType referenced by message objects defined
 * by the GreenballMessages grammar.
 */
public class Include {
   private static final int ID = GreenballMessagesEnum.INCLUDE.getId();

   /**
    * The number of bits required to represent the IncludeEnum IDs.
    * # of attributes: 1
    * # of PEnumRefs: 0
    */
   private static final int ID_BITS = 0;

   private static GreenballMessagesDirectoryEntry[] theDirectory;
   private static final int DIRECTORY_OFFSET = 0;

   private static Logger log4j = Logger.getLogger(Include.class);

   // Entered buildClassEnum()
   private enum IncludeEnum {
      // This is a directory item. It's offset and length cannot be determined
      // until runtime.
      INCLUDE_NAMESPACE(0, -1, 0, true);

      private final int id;
      private final int offsetInBits;
      private int length;
      private boolean isDirectoryEntry;

      IncludeEnum(int id, int offsetInBits, int length, boolean isDirectoryEntry) {
         this.id = id;
         this.offsetInBits = offsetInBits;
         this.length = length;
         this.isDirectoryEntry = isDirectoryEntry;
      }

      public int getId() {
         return this.id;
      }

      public int getOffsetInBits() {
         return this.offsetInBits;
      }

      public int getLength() {
         return this.length;
      }

      public void setLength(int length) {
         this.length = length;
      }
   } // Leaving buildClassEnum()

   /*
    * The instance variables.
    * See buildInstanceVariables() in JBitByBitGenerator.java.
    */
   private String includeNamespace;

   private String theErrorMsg;

   /**
    * The Include no-arg constructor.
    */
   public Include() {}

   /**
    * The Include constructor.
    * See buildParameterAnnotations() in JBitByBitGenerator.java.
    *
    * @param includeNamespace The includeNamespace message attribute.
    */
   public Include(String includeNamespace) {
      // Entered buildParameterAssignments()
      this.setIncludeNamespace(includeNamespace);
      // Leaving buildParameterAssignments()
   }

   /**
    * The Include copy constructor.
    */
   public Include(Include include) {
      // Entered buildCopyConstructorParameterAssignments()
      this.setIncludeNamespace(include.getIncludeNamespace());
      // Leaving buildCopyConstructorParameterAssignments()
   }

   // Entered buildSetErrorMsgMethod()
   private void setErrorMsg(String errorMsg) {
      theErrorMsg = errorMsg;
   }
   // Leaving buildSetErrorMsgMethod()

   // Entered buildGetErrorMsgMethod()
   /**
    * This method returns the error message or null if no error
    * occurred.
    */
   public String getErrorMsg() {
      return theErrorMsg;
   }
   // Leaving buildGetErrorMsgMethod()

   // Entered buildPackMethod()
   /**
    * This method packs a Include object into a byte array. If a required attribute is not
    * provided an exception will be thrown.
    *
    * @return A byte array which represents a Include message object.
    * @throws MissingAttributeException
    */
   public byte[] pack() throws MissingAttributeException {
      final String METHOD = "pack()";
      log4j.debug("Entered " + METHOD);

      int byteArraySize = getIncludeSize();
      log4j.debug("byteArraySize: " + byteArraySize);
      byte[] bb = new byte[byteArraySize];

      /*
       * Convert object to byte array.
       */
      int offset = 0;


      IncludeEnum.INCLUDE_NAMESPACE.setLength(this.getIncludeNamespace() != null ? this.getIncludeNamespace().length() : 0);

      int directorySize = getIncludeDirectorySize();
      if (directorySize != 0) {
         // Create the directory
         theDirectory = new GreenballMessagesDirectoryEntry[directorySize];
         for (int i = 0; i < directorySize; i++) {
            theDirectory[i] = new GreenballMessagesDirectoryEntry();
         }

         // Fill the directory
         int index = 0;
         offset = DIRECTORY_OFFSET
               + GreenballMessagesDirectoryEntry.DIRECTORY_ENTRY_SIZE_IN_BYTES
               * theDirectory.length;

         for (IncludeEnum includeEnum : IncludeEnum.values()) {
            if (includeEnum.isDirectoryEntry == true) {
               int id = includeEnum.getId();
               int length = includeEnum.getLength();

               theDirectory[index].setId(id);
               theDirectory[index].setLength(length);
               theDirectory[index].setOffset(offset);

               // Insert the data
               if (id == IncludeEnum.INCLUDE_NAMESPACE.getId()) {
                  log4j.debug(String.format("inserting %s at offset %d", "includeNamespace", offset));
                  if (getIncludeNamespace() != null) {
                     bb = GreenballMessagesUtility.insertString(bb, offset, getIncludeNamespace());
                     offset += length * 1;
                  }
               }
               index++;
            }
         }

         // Insert the directory
         log4j.debug(String.format("inserting the directory at offset %d", DIRECTORY_OFFSET));
         offset = DIRECTORY_OFFSET;
         index = 0;
         for (GreenballMessagesDirectoryEntry directoryEntry : theDirectory) {
            log4j.debug(String.format("index[%d]: ", index));
            log4j.debug(String.format("  ID:     %d", directoryEntry.getId()));
            log4j.debug(String.format("  length: %d", directoryEntry.getLength()));
            log4j.debug(String.format("  offset: %d", directoryEntry.getOffset()));
            bb = GreenballMessagesUtility.insertInteger(bb, offset, directoryEntry.getId());
            bb = GreenballMessagesUtility.insertInteger(bb, offset + 4, directoryEntry.getLength());
            bb = GreenballMessagesUtility.insertInteger(bb, offset + 8, directoryEntry.getOffset());

            offset += GreenballMessagesDirectoryEntry.DIRECTORY_ENTRY_SIZE_IN_BYTES;
            index++;
         }

      }
      log4j.debug("Leaving " + METHOD);
      return bb;
   }
   // Leaving buildPackMethod()

   // Entered buildUnpackMethod()
   /**
    * This method unpacks a byte array containing a Include object.
    *
    * @return The byte array as a Include message object.
    */
   public Include unpack(byte[] ba) {
      final String METHOD = "unpack()";
      log4j.debug("Entered " + METHOD);

      Include include = new Include();


      // Get the directory
      int directorySize = getIncludeDirectorySize();
      theDirectory = new GreenballMessagesDirectoryEntry[directorySize];
      int dirOffset = DIRECTORY_OFFSET;

      for (int entry = 0 ; entry < directorySize; entry++) {
         GreenballMessagesDirectoryEntry directoryEntry = new GreenballMessagesDirectoryEntry();

         int id = GreenballMessagesUtility.getInteger(ba, dirOffset * 8);
         directoryEntry.setId(id);
         int length = GreenballMessagesUtility.getInteger(ba, (dirOffset + 4) * 8);
         directoryEntry.setLength(length);
         int offset = GreenballMessagesUtility.getInteger(ba, (dirOffset + 8) * 8);
         directoryEntry.setOffset(offset);

         theDirectory[entry] = directoryEntry;

         dirOffset += GreenballMessagesDirectoryEntry.DIRECTORY_ENTRY_SIZE_IN_BYTES;
      }

      for (GreenballMessagesDirectoryEntry directoryEntry : theDirectory) {
         int id = directoryEntry.getId();
         int offset = directoryEntry.getOffset();
         int length = directoryEntry.getLength();

         if (id == IncludeEnum.INCLUDE_NAMESPACE.getId()) {
            include.setIncludeNamespace(GreenballMessagesUtility.getString(ba, offset, length));
         }
      }

      log4j.debug("Leaving " + METHOD);
      return include;
   }
   // Leaving buildUnpackMethod()

   /**
    * This method sets the includeNamespace attribute. Setting of this value is required.
    * @param includeNamespace The includeNamespace attribute.
    */
   public void setIncludeNamespace(String includeNamespace) {
      this.includeNamespace = includeNamespace;
   }

   /**
    * This method gets the includeNamespace attribute. The includeNamespace attribute is a required attribute.
    */
   public String getIncludeNamespace() {
      return this.includeNamespace;
   }

   /**
    * This method gets the size of the directory.
    */
   private int getIncludeDirectorySize() {
      int directorySize = 0;

      // includeNamespace
      directorySize++;

      return directorySize;
   }


   /**
    * This method gets the size of the Include object.
    * @return The size in bytes.
    */
   public int getIncludeSize() {
      int size = 0;

      int directorySize = getIncludeDirectorySize();
      size += directorySize * GreenballMessagesDirectoryEntry.DIRECTORY_ENTRY_SIZE_IN_BYTES;
      // Add size of includeNamespace
      size += (getIncludeNamespace() != null ? getIncludeNamespace().length() : 0);

      return size;
   }

   @Override
   public String toString() {
      StringBuilder result = new StringBuilder();
      String NEW_LINE = System.getProperty("line.separator");

      result.append(this.getClass().getSimpleName() + " Object {" + NEW_LINE);
      result.append(" includeNamespace: " + includeNamespace + NEW_LINE);

      result.append("} ");

      return result.toString();
   }

   /**
    * The hashCode method returns this object's hashCode.
    */
   @Override
   public int hashCode() {
      final int prime = 31;
      int result = 1;
      result = prime * result
         + ((String) includeNamespace).hashCode();
      return result;
   }

   /**
    * The equals method checks for equality. 
    */
   public boolean equals(Object obj) {
      if (obj == this) return true;
      if (obj == null) return false;
      if (getClass() != obj.getClass()) return false;

      Include include = (Include) obj;
      if (!include.getIncludeNamespace().equals(this.getIncludeNamespace())) {
         return false;
      }

      return true;
   }
}
