/*
 * WARNING: This file was generated by BitByBitGenerator.xtend (see
 * generateInitializationFile()). 
 * Do not edit.
 */
package com.viacron.greenball.app.bbb;
import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import com.viacron.utils.StringMessageBuffer.parser.AbstractAttribute;
import com.viacron.utils.StringMessageBuffer.parser.Element;
import com.viacron.utils.StringMessageBuffer.parser.KeyValuePair;

/**
 * The InitializeUpdateRuleDeadline class initializes the element object with the UpdateRuleDeadline object.
 *
 */
public class InitializeUpdateRuleDeadline {
   private static Logger log4j = Logger.getLogger(InitializeUpdateRuleDeadline.class);
   private String theErrorMsg;
   private Element element;
   private UpdateRuleDeadline updateRuleDeadline;

   /**
    * The InitializeUpdateRuleDeadline class initializes the element object with the UpdateRuleDeadline object.
    *
    * @param updateRuleDeadline The object which will be used to initialize the element object.
    */
   public InitializeUpdateRuleDeadline(UpdateRuleDeadline updateRuleDeadline) {
      this.updateRuleDeadline = updateRuleDeadline;

      this.element = new Element("UpdateRuleDeadline");
   }

   /**
    * This method initializes the element.
    */
   public Element initialize() throws MissingAttributeException {
      final String METHOD = "initialize()";
      log4j.debug("Entered " + METHOD);

      log4j.debug("element.getName(): UpdateRuleDeadline");

      if (updateRuleDeadline.getRuleId() != null) {
         AbstractAttribute abstractAttribute = initializeRuleId(updateRuleDeadline.getRuleId());
         element.getAbstractAttributes().add(abstractAttribute);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"ruleId\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }

      if (updateRuleDeadline.getNewDeadlineMsec() != null) {
         AbstractAttribute abstractAttribute = initializeNewDeadlineMsec(updateRuleDeadline.getNewDeadlineMsec());
         element.getAbstractAttributes().add(abstractAttribute);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"newDeadlineMsec\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }

      if (updateRuleDeadline.getOldDeadlineMsec() != null) {
         AbstractAttribute abstractAttribute = initializeOldDeadlineMsec(updateRuleDeadline.getOldDeadlineMsec());
         element.getAbstractAttributes().add(abstractAttribute);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"oldDeadlineMsec\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }

      if (updateRuleDeadline.getSessionId() != null) {
         AbstractAttribute abstractAttribute = initializeSessionId(updateRuleDeadline.getSessionId());
         element.getAbstractAttributes().add(abstractAttribute);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"sessionId\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }


      log4j.debug("Leaving " + METHOD);
      return element;
   }

   /*
    * This method initializes the ruleId attribute.
    * Generated by initAttributeMethods()
    */
   private AbstractAttribute initializeRuleId(String ruleId)
         throws MissingAttributeException {
      AbstractAttribute abstractAttribute = new AbstractAttribute();
      // Entered initAbstractAttributeValue()
      // Entered initAttributeValue()
      if (ruleId != null) {
         log4j.debug("Creating new KeyValuePair: ruleId");
         KeyValuePair kvp = new KeyValuePair("ruleId", "<STRING_BEGIN>" + ruleId + "<STRING_END>");
         abstractAttribute.getKeyValuePairs().add(kvp);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"ruleId\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }

      // Leaving initAttributeValue()
      // Leaving initAbstractAttributeValue()
      return abstractAttribute;
   }

   /*
    * This method initializes the newDeadlineMsec attribute.
    * Generated by initAttributeMethods()
    */
   private AbstractAttribute initializeNewDeadlineMsec(Long newDeadlineMsec)
         throws MissingAttributeException {
      AbstractAttribute abstractAttribute = new AbstractAttribute();
      // Entered initAbstractAttributeValue()
      // Entered initAttributeValue()
      if (newDeadlineMsec != null) {
         log4j.debug("Creating new KeyValuePair: newDeadlineMsec");
         KeyValuePair kvp = new KeyValuePair("newDeadlineMsec", Long.toString(newDeadlineMsec));
         abstractAttribute.getKeyValuePairs().add(kvp);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"newDeadlineMsec\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }

      // Leaving initAttributeValue()
      // Leaving initAbstractAttributeValue()
      return abstractAttribute;
   }

   /*
    * This method initializes the oldDeadlineMsec attribute.
    * Generated by initAttributeMethods()
    */
   private AbstractAttribute initializeOldDeadlineMsec(Long oldDeadlineMsec)
         throws MissingAttributeException {
      AbstractAttribute abstractAttribute = new AbstractAttribute();
      // Entered initAbstractAttributeValue()
      // Entered initAttributeValue()
      if (oldDeadlineMsec != null) {
         log4j.debug("Creating new KeyValuePair: oldDeadlineMsec");
         KeyValuePair kvp = new KeyValuePair("oldDeadlineMsec", Long.toString(oldDeadlineMsec));
         abstractAttribute.getKeyValuePairs().add(kvp);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"oldDeadlineMsec\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }

      // Leaving initAttributeValue()
      // Leaving initAbstractAttributeValue()
      return abstractAttribute;
   }

   /*
    * This method initializes the sessionId attribute.
    * Generated by initAttributeMethods()
    */
   private AbstractAttribute initializeSessionId(String sessionId)
         throws MissingAttributeException {
      AbstractAttribute abstractAttribute = new AbstractAttribute();
      // Entered initAbstractAttributeValue()
      // Entered initAttributeValue()
      if (sessionId != null) {
         log4j.debug("Creating new KeyValuePair: sessionId");
         KeyValuePair kvp = new KeyValuePair("sessionId", "<STRING_BEGIN>" + sessionId + "<STRING_END>");
         abstractAttribute.getKeyValuePairs().add(kvp);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"sessionId\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }

      // Leaving initAttributeValue()
      // Leaving initAbstractAttributeValue()
      return abstractAttribute;
   }

   /**
   * This method returns the error message or null if no error occurred.
   */
   public String getErrorMsg() {
      return theErrorMsg;
   }

   private void setErrorMsg(String errorMsg) {
      theErrorMsg = errorMsg;
   }

}
