/*
 * WARNING: This file was generated by BitByBitGenerator.xtend (see
 * generateInstantiationFile()). 
 * Do not edit.
 */
package com.viacron.greenball.app.bbb;
import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import com.viacron.utils.StringMessageBuffer.parser.AbstractAttribute;
import com.viacron.utils.StringMessageBuffer.parser.Element;
import com.viacron.utils.StringMessageBuffer.parser.KeyValuePair;

public class InstantiateDeleteRuleMessageResponse {
   private static Logger log4j = Logger.getLogger(InstantiateDeleteRuleMessageResponse.class);

   /*
    * The isUpdated flags. If an attribute is required by the grammar then a value
    * must be provided, and the isUpdated flag will be set when the value is
    * obtained during unpacking. After the object is constructed during unpacking, 
    * validation will be performed to make sure a value was provided for all attributes
    * that are not optional. 
    * See buildFlags() in JBitByBitGenerator.java.
    */
   private boolean isOrgIdUpdated = false;
   private boolean isOrgNameUpdated = false;
   private boolean isModelNameUpdated = false;
   private boolean isRuleIdUpdated = false;
   private boolean isRuleNameUpdated = false;
   private boolean isUserNameUpdated = false;
   private boolean isIsDeletedUpdated = false;

   private Element element;
   private DeleteRuleMessageResponse deleteRuleMessageResponse;

   /**
    * The InstantiateDeleteRuleMessageResponse class instantiates the DeleteRuleMessageResponse object.
    *
    * @param element The root element returned by the parser after parsing the string
    *                representing the DeleteRuleMessageResponse.
    */
   public InstantiateDeleteRuleMessageResponse(Element element) {
      this.element = element;   
      this.deleteRuleMessageResponse = new DeleteRuleMessageResponse();
   }

   /**
    * This method instantiates the DeleteRuleMessageResponse.
    *
    * @return The DeleteRuleMessageResponse.
    */
   public DeleteRuleMessageResponse instantiate() {
      final String METHOD = "instantiate()";
      log4j.debug("Entered " + METHOD);

      log4j.debug("DeleteRuleMessageResponse: " + element.getName());
      log4j.debug("# of attributes: " + element.getAbstractAttributes().size());

      instantiateDeleteRuleMessageResponseAttributes(element);

      for (AbstractAttribute abstractAttribute : element
            .getAbstractAttributes()) {
         for (Element e : abstractAttribute.getElements()) {
            log4j.debug("element name: " + e.getName());
      instantiateDeleteRuleMessageResponseSubTypeRefs(e);
      }
      }

      log4j.debug("Leaving " + METHOD);
      return deleteRuleMessageResponse;
      }

      /*
       * This method instantiates the DeleteRuleMessageResponse attributes.
       * 
       * @param Element element
       */
      private void instantiateDeleteRuleMessageResponseAttributes(Element element) {
      final String METHOD = "instantiateDeleteRuleMessageResponseAttributes()";
      log4j.debug("Entered " + METHOD);

      log4j.debug("element name: " + element.getName());
      for (AbstractAttribute attr : element.getAbstractAttributes()) {
         for (KeyValuePair kvp : attr.getKeyValuePairs()) {
            log4j.debug("key: " + kvp.getKey());
            log4j.debug("value: " + kvp.getValue());
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("orgId")) {
               log4j.debug("setting value of \"orgId\" to: " + kvp.getValue());
               this.isOrgIdUpdated = true;
               deleteRuleMessageResponse.setOrgId(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("orgName")) {
               log4j.debug("setting value of \"orgName\" to: " + kvp.getValue());
               this.isOrgNameUpdated = true;
               deleteRuleMessageResponse.setOrgName(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("modelName")) {
               log4j.debug("setting value of \"modelName\" to: " + kvp.getValue());
               this.isModelNameUpdated = true;
               deleteRuleMessageResponse.setModelName(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("ruleId")) {
               log4j.debug("setting value of \"ruleId\" to: " + kvp.getValue());
               this.isRuleIdUpdated = true;
               deleteRuleMessageResponse.setRuleId(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("ruleName")) {
               log4j.debug("setting value of \"ruleName\" to: " + kvp.getValue());
               this.isRuleNameUpdated = true;
               deleteRuleMessageResponse.setRuleName(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("userName")) {
               log4j.debug("setting value of \"userName\" to: " + kvp.getValue());
               this.isUserNameUpdated = true;
               deleteRuleMessageResponse.setUserName(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("isDeleted")) {
               log4j.debug("setting value of \"isDeleted\" to: " + kvp.getValue());
               this.isIsDeletedUpdated = true;
               deleteRuleMessageResponse.setIsDeleted(kvp.getValue().equals("true"));
            }
            // Leaving instantiateMsgAttribute()
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("sessionId")) {
               log4j.debug("setting value of \"sessionId\" to: " + kvp.getValue());
               deleteRuleMessageResponse.setSessionId(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
         }
      }

      log4j.debug("Leaving " + METHOD);
   }

   /*
    * This method instantiates the DeleteRuleMessageResponse SubType references.
    * 
    * @param Element element
    */
   private void instantiateDeleteRuleMessageResponseSubTypeRefs(Element element) {
      final String METHOD = "instantiateDeleteRuleMessageResponseSubTypeRefs()";
      log4j.debug("Entered " + METHOD);


      log4j.debug("Leaving " + METHOD);
   }


   /**
    * The validate method checks that a value was provided for all required 
    * attributes.
    *
    * @return The error message or null if no error occurred.
    */
   protected String validate() {
      final String METHOD = "validate()";
      log4j.debug("Entered " + METHOD);

      String result = null;

      // Entered buildValidationMethod()
      if (!this.isOrgIdUpdated) {
         String msg = "OrgId is required, but no value was provided.";
         if (result == null) {
            result = msg;
         }
      }

      if (!this.isOrgNameUpdated) {
         String msg = "OrgName is required, but no value was provided.";
         if (result == null) {
            result = msg;
         }
         else {
            result = result.concat("\n" + msg);
         }
      }

      if (!this.isModelNameUpdated) {
         String msg = "ModelName is required, but no value was provided.";
         if (result == null) {
            result = msg;
         }
         else {
            result = result.concat("\n" + msg);
         }
      }

      if (!this.isRuleIdUpdated) {
         String msg = "RuleId is required, but no value was provided.";
         if (result == null) {
            result = msg;
         }
         else {
            result = result.concat("\n" + msg);
         }
      }

      if (!this.isRuleNameUpdated) {
         String msg = "RuleName is required, but no value was provided.";
         if (result == null) {
            result = msg;
         }
         else {
            result = result.concat("\n" + msg);
         }
      }

      if (!this.isUserNameUpdated) {
         String msg = "UserName is required, but no value was provided.";
         if (result == null) {
            result = msg;
         }
         else {
            result = result.concat("\n" + msg);
         }
      }

      if (!this.isIsDeletedUpdated) {
         String msg = "IsDeleted is required, but no value was provided.";
         if (result == null) {
            result = msg;
         }
         else {
            result = result.concat("\n" + msg);
         }
      }


      if (result != null) {
         log4j.debug("result: " + result);
      }

      log4j.debug("Leaving " + METHOD);
      return result;
   }
}
