/*
 * WARNING: This file was generated by BitByBitGenerator.xtend (see
 * generateClassFile()). 
 * Do not edit.
 */
package com.viacron.greenball.app.bbb;

import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.log4j.Logger;
import org.antlr.runtime.ANTLRStringStream;
import org.antlr.runtime.CommonTokenStream;
import org.antlr.runtime.RecognitionException;

import com.viacron.utils.StringMessageBuffer.parser.AbstractAttribute;
import com.viacron.utils.StringMessageBuffer.parser.Element;
import com.viacron.utils.StringMessageBuffer.parser.KeyValuePair;
import com.viacron.utils.StringMessageBuffer.parser.SMBGLexer;
import com.viacron.utils.StringMessageBuffer.parser.SMBGParser;

/**
 * The ResponseChangePassword class defines a message of the messaging system defined
 * by the GreenballMessages grammar. It provides methods for packing a ResponseChangePassword object
 * into a byte array or string, and for unpacking a byte array or string
 * back into a ResponseChangePassword object.
 */
public class ResponseChangePassword {
   private static final int ID = GreenballMessagesEnum.RESPONSE_CHANGE_PASSWORD.getId();

   /**
    * The number of bits required to represent the ResponseChangePasswordEnum IDs.
    * # of attributes: 4
    * # of PEnumRefs: 0
    */
   private static final int ID_BITS = 2;

   private static GreenballMessagesDirectoryEntry[] theDirectory;
   private static final int DIRECTORY_OFFSET = 3;

   private static Logger log4j = Logger.getLogger(ResponseChangePassword.class);

   // Entered buildClassEnum()
   private enum ResponseChangePasswordEnum {
      // This is a directory item. It's offset and length cannot be determined
      // until runtime.
      USER(0, -1, 0, true),

      // This is a directory item. It's offset and length cannot be determined
      // until runtime.
      NEW_PASSWORD(1, -1, 0, true),

      // sizeInBits: 8
      CHANGED(2, 16, 0, false),

      // This is a directory item. It's offset and length cannot be determined
      // until runtime.
      SESSION_ID(3, -1, 0, true);

      private final int id;
      private final int offsetInBits;
      private int length;
      private boolean isDirectoryEntry;

      ResponseChangePasswordEnum(int id, int offsetInBits, int length, boolean isDirectoryEntry) {
         this.id = id;
         this.offsetInBits = offsetInBits;
         this.length = length;
         this.isDirectoryEntry = isDirectoryEntry;
      }

      public int getId() {
         return this.id;
      }

      public int getOffsetInBits() {
         return this.offsetInBits;
      }

      public int getLength() {
         return this.length;
      }

      public void setLength(int length) {
         this.length = length;
      }
   } // Leaving buildClassEnum()

   /*
    * The instance variables.
    * See buildInstanceVariables() in JBitByBitGenerator.java.
    */
   private String user;
   private String newPassword;
   private boolean changed;
   private String sessionId;

   private String theErrorMsg;

   /**
    * The ResponseChangePassword no-arg constructor.
    */
   public ResponseChangePassword() {}

   /**
    * The ResponseChangePassword constructor.
    * See buildParameterAnnotations() in JBitByBitGenerator.java.
    *
    * @param user The user message attribute.
    * @param newPassword The newPassword message attribute.
    * @param changed The changed message attribute.
    * @param sessionId The sessionId message attribute.
    */
   public ResponseChangePassword(String user,
                                 String newPassword,
                                 Boolean changed,
                                 String sessionId) {
      // Entered buildParameterAssignments()
      this.setUser(user);
      this.setNewPassword(newPassword);
      this.setChanged(changed);
      this.setSessionId(sessionId);
      // Leaving buildParameterAssignments()
   }


   // Entered buildSetErrorMsgMethod()
   private void setErrorMsg(String errorMsg) {
      theErrorMsg = errorMsg;
   }
   // Leaving buildSetErrorMsgMethod()

   // Entered buildGetErrorMsgMethod()
   /**
    * This method returns the error message or null if no error
    * occurred.
    */
   public String getErrorMsg() {
      return theErrorMsg;
   }
   // Leaving buildGetErrorMsgMethod()

   // Entered buildPackMethod()
   /**
    * This method packs a ResponseChangePassword object into a byte array. If a required attribute is not
    * provided an exception will be thrown.
    *
    * @return A byte array which represents a ResponseChangePassword message object.
    * @throws MissingAttributeException
    */
   public byte[] pack() throws MissingAttributeException {
      final String METHOD = "pack()";
      log4j.debug("Entered " + METHOD);

      int byteArraySize = getResponseChangePasswordSize();
      log4j.debug("byteArraySize: " + byteArraySize);
      byte[] bb = new byte[byteArraySize];

      /*
       * Convert object to byte array.
       */
      int offset = 0;

      bb = GreenballMessagesUtility.insertShort(bb, offset, (short) ID);
      offset += 2;

      if (this.getChanged() != null) {
         log4j.debug(String.format("inserting %s at offset %d", "changed", offset));
         bb = GreenballMessagesUtility.insertBitfield(bb, offset * 8, 1, this.getChanged() == true ? 1 : 0);
         offset += 1;
      } else {
         /*
          * Missing required attribute, generate an error message and throw
          * an exception.
          */
         setErrorMsg("Error packing object. The attribute \"changed\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }


      ResponseChangePasswordEnum.USER.setLength(this.getUser() != null ? this.getUser().length() : 0);
      ResponseChangePasswordEnum.NEW_PASSWORD.setLength(this.getNewPassword() != null ? this.getNewPassword().length() : 0);
      ResponseChangePasswordEnum.SESSION_ID.setLength(this.getSessionId() != null ? this.getSessionId().length() : 0);

      int directorySize = getResponseChangePasswordDirectorySize();
      if (directorySize != 0) {
         // Create the directory
         theDirectory = new GreenballMessagesDirectoryEntry[directorySize];
         for (int i = 0; i < directorySize; i++) {
            theDirectory[i] = new GreenballMessagesDirectoryEntry();
         }

         // Fill the directory
         int index = 0;
         offset = DIRECTORY_OFFSET
               + GreenballMessagesDirectoryEntry.DIRECTORY_ENTRY_SIZE_IN_BYTES
               * theDirectory.length;

         for (ResponseChangePasswordEnum responseChangePasswordEnum : ResponseChangePasswordEnum.values()) {
            if (responseChangePasswordEnum.isDirectoryEntry == true) {
               int id = responseChangePasswordEnum.getId();
               int length = responseChangePasswordEnum.getLength();

               theDirectory[index].setId(id);
               theDirectory[index].setLength(length);
               theDirectory[index].setOffset(offset);

               // Insert the data
               if (id == ResponseChangePasswordEnum.USER.getId()) {
                  log4j.debug(String.format("inserting %s at offset %d", "user", offset));
                  if (getUser() != null) {
                     bb = GreenballMessagesUtility.insertString(bb, offset, getUser());
                     offset += length * 1;
                  }
               }
               else if (id == ResponseChangePasswordEnum.NEW_PASSWORD.getId()) {
                  log4j.debug(String.format("inserting %s at offset %d", "newPassword", offset));
                  if (getNewPassword() != null) {
                     bb = GreenballMessagesUtility.insertString(bb, offset, getNewPassword());
                     offset += length * 1;
                  }
               }
               else if (id == ResponseChangePasswordEnum.SESSION_ID.getId()) {
                  log4j.debug(String.format("inserting %s at offset %d", "sessionId", offset));
                  if (getSessionId() != null) {
                     bb = GreenballMessagesUtility.insertString(bb, offset, getSessionId());
                     offset += length * 1;
                  }
               }
               index++;
            }
         }

         // Insert the directory
         log4j.debug(String.format("inserting the directory at offset %d", DIRECTORY_OFFSET));
         offset = DIRECTORY_OFFSET;
         index = 0;
         for (GreenballMessagesDirectoryEntry directoryEntry : theDirectory) {
            log4j.debug(String.format("index[%d]: ", index));
            log4j.debug(String.format("  ID:     %d", directoryEntry.getId()));
            log4j.debug(String.format("  length: %d", directoryEntry.getLength()));
            log4j.debug(String.format("  offset: %d", directoryEntry.getOffset()));
            bb = GreenballMessagesUtility.insertInteger(bb, offset, directoryEntry.getId());
            bb = GreenballMessagesUtility.insertInteger(bb, offset + 4, directoryEntry.getLength());
            bb = GreenballMessagesUtility.insertInteger(bb, offset + 8, directoryEntry.getOffset());

            offset += GreenballMessagesDirectoryEntry.DIRECTORY_ENTRY_SIZE_IN_BYTES;
            index++;
         }

         // Calculate and insert the checksum
         long checksum = GreenballMessagesUtility.getChecksum(bb, bb.length - 8);
         bb = GreenballMessagesUtility.insertLong(bb, bb.length - 8, checksum);
      }
      log4j.debug("Leaving " + METHOD);
      return bb;
   }
   // Leaving buildPackMethod()

   // Entered buildUnpackMethod()
   /**
    * This method unpacks a byte array containing a ResponseChangePassword object.
    *
    * @return The byte array as a ResponseChangePassword message object.
    */
   public ResponseChangePassword unpack(byte[] ba) {
      final String METHOD = "unpack()";
      log4j.debug("Entered " + METHOD);

      ResponseChangePassword responseChangePassword = new ResponseChangePassword();

      responseChangePassword.setChanged(GreenballMessagesUtility.getBoolean(ba, ResponseChangePasswordEnum.CHANGED.getOffsetInBits()));

      // Get the directory
      int directorySize = getResponseChangePasswordDirectorySize();
      theDirectory = new GreenballMessagesDirectoryEntry[directorySize];
      int dirOffset = DIRECTORY_OFFSET;

      for (int entry = 0 ; entry < directorySize; entry++) {
         GreenballMessagesDirectoryEntry directoryEntry = new GreenballMessagesDirectoryEntry();

         int id = GreenballMessagesUtility.getInteger(ba, dirOffset * 8);
         directoryEntry.setId(id);
         int length = GreenballMessagesUtility.getInteger(ba, (dirOffset + 4) * 8);
         directoryEntry.setLength(length);
         int offset = GreenballMessagesUtility.getInteger(ba, (dirOffset + 8) * 8);
         directoryEntry.setOffset(offset);

         theDirectory[entry] = directoryEntry;

         dirOffset += GreenballMessagesDirectoryEntry.DIRECTORY_ENTRY_SIZE_IN_BYTES;
      }

      for (GreenballMessagesDirectoryEntry directoryEntry : theDirectory) {
         int id = directoryEntry.getId();
         int offset = directoryEntry.getOffset();
         int length = directoryEntry.getLength();

         if (id == ResponseChangePasswordEnum.USER.getId()) {
            responseChangePassword.setUser(GreenballMessagesUtility.getString(ba, offset, length));
         }
         else if (id == ResponseChangePasswordEnum.NEW_PASSWORD.getId()) {
            responseChangePassword.setNewPassword(GreenballMessagesUtility.getString(ba, offset, length));
         }
         else if (id == ResponseChangePasswordEnum.SESSION_ID.getId()) {
            responseChangePassword.setSessionId(GreenballMessagesUtility.getString(ba, offset, length));
         }
      }

      log4j.debug("Leaving " + METHOD);
      return responseChangePassword;
   }
   // Leaving buildUnpackMethod()

   // Entered buildPackStrMethod()
   /**
    * This method packs a ResponseChangePassword object into a String. If a required attribute is not
    * provided an exception will be thrown.
    *
    * @return A String which represents a ResponseChangePassword message object.
    * @throws MissingAttributeException
    */
   public String packStr() throws MissingAttributeException {
      final String METHOD = "packStr()";
      log4j.debug("Entered " + METHOD);

      String msg = null;
      setErrorMsg(null);
       
      /*
       * Initialize attribute values.
       */
      InitializeResponseChangePassword initializeResponseChangePassword = new InitializeResponseChangePassword(this);
      Element element = initializeResponseChangePassword.initialize();

      if (getErrorMsg() == null) {
         /*
          * Convert object to String.
          * See convertObjectToString() in JBitByBitGenerator.java.
          */
         msg = "{" + element.getName();
         for (AbstractAttribute attr : element.getAbstractAttributes()) {
            msg = buildString(attr, msg);
         }
         msg = msg.concat("}");

         log4j.debug("msg: " + msg);
      }

      log4j.debug("Leaving " + METHOD);
      return msg;
   }
   // Leaving buildPackStrMethod()

   // Entered buildUnpackStrMethod()
   /**
    * The unpack() method unpacks a String into an object. The String must conform to the
    * SMBG grammar.
    *
     * @return The message string as an object.
    */
   public ResponseChangePassword unpack(String buffer) {
      final String METHOD = "unpack()";
      log4j.debug("Entered " + METHOD);

      setErrorMsg(null);

      // Create the lexer
      log4j.debug("lexing...");
      SMBGLexer lexer = new SMBGLexer(new ANTLRStringStream(buffer));

      int nbrOfSyntaxErrors = lexer.getNumberOfSyntaxErrors();
      log4j.debug("# of lexer errors: " + nbrOfSyntaxErrors);

      // Check for errors
      if (nbrOfSyntaxErrors != 0) {
         for (String error : lexer.getErrors()) {
            log4j.error(error);
         }

         return null;
      }

      // Wrap a token-stream around the lexer
      CommonTokenStream tokenStream = new CommonTokenStream(lexer);

      // Create the parser
      log4j.debug("parsing...");
      SMBGParser parser = new SMBGParser(tokenStream);

      // Check for errors
      nbrOfSyntaxErrors = parser.getNumberOfSyntaxErrors();
      log4j.debug("# of parse errors: " + nbrOfSyntaxErrors);

      if (nbrOfSyntaxErrors != 0) {
         for (String error : parser.getErrors()) {
               log4j.error(error);
         }

         return null;
      }

      // Unpack the string into objects
      log4j.debug("unpacking...");
      try {
         parser.unpack();
      } catch (RecognitionException e) {
         log4j.error("Error: " + e.getMessage());
         setErrorMsg(e.getMessage());
         return null;
      }
      
      Element element = parser.getElement();
      element.dump();

      /*
       * Instantiate the ResponseChangePassword object.
       */
       InstantiateResponseChangePassword instantiateResponseChangePassword = new InstantiateResponseChangePassword(element);
       ResponseChangePassword responseChangePassword = instantiateResponseChangePassword.instantiate();

      /*
       * Verify that a value was provided for all mandatory attributes.
       */
      String result = instantiateResponseChangePassword.validate();
      if (result != null) {
         log4j.error("Error: " + result);
         setErrorMsg(result);
         return null;
      }

      log4j.debug("Leaving " + METHOD);
      return responseChangePassword;
   }
   // Leaving buildUnpackStrMethod()

   private String buildString(AbstractAttribute attr, String msg) {
      for (KeyValuePair kvp : attr.getKeyValuePairs()) {
         msg = msg.concat(" " + kvp.getKey() + ":" + kvp.getValue());
      }

      for (Element element : attr.getElements()) {
         msg = msg.concat(" {" + element.getName());
         for (AbstractAttribute abstractAttribute : element.getAbstractAttributes()) {
            msg = buildString(abstractAttribute, msg);
         }
         msg = msg.concat("}");
      }

      return msg;
   }

   /**
    * This method sets the user attribute. Setting of this value is required.
    * @param user The user attribute.
    */
   public void setUser(String user) {
      this.user = user;
   }

   /**
    * This method sets the newPassword attribute. Setting of this value is optional.
    * @param newPassword The newPassword attribute.
    */
   public void setNewPassword(String newPassword) {
      this.newPassword = newPassword;
   }

   /**
    * This method sets the changed attribute. Setting of this value is required.
    * @param changed The changed attribute.
    */
   public void setChanged(Boolean changed) {
      this.changed = changed;
   }

   /**
    * This method sets the sessionId attribute. Setting of this value is required.
    * @param sessionId The sessionId attribute.
    */
   public void setSessionId(String sessionId) {
      this.sessionId = sessionId;
   }

   /**
    * This method gets the user attribute. The user attribute is a required attribute.
    */
   public String getUser() {
      return this.user;
   }

   /**
    * This method gets the newPassword attribute. The newPassword attribute is an optional attribute.
    */
   public String getNewPassword() {
      return this.newPassword;
   }

   /**
    * This method gets the changed attribute. The changed attribute is a required attribute.
    */
   public Boolean getChanged() {
      return this.changed;
   }

   /**
    * This method gets the sessionId attribute. The sessionId attribute is a required attribute.
    */
   public String getSessionId() {
      return this.sessionId;
   }

   /**
    * This method gets the size of the directory.
    */
   private int getResponseChangePasswordDirectorySize() {
      int directorySize = 0;

      // user
      directorySize++;
      // newPassword
      directorySize++;
      // sessionId
      directorySize++;

      return directorySize;
   }


   /**
    * This method gets the size of the ResponseChangePassword object.
    * @return The size in bytes.
    */
   public int getResponseChangePasswordSize() {
      int size = 0;

      int directorySize = getResponseChangePasswordDirectorySize();
      size += directorySize * GreenballMessagesDirectoryEntry.DIRECTORY_ENTRY_SIZE_IN_BYTES;
      // Add two bytes for the ID
      size += 2;
      // Add eight bytes for the CRC
      size += 8;
      // Add size of user
      size += (getUser() != null ? getUser().length() : 0);
      // Add size of newPassword
      size += (getNewPassword() != null ? getNewPassword().length() : 0);
      // Add size of changed
      size += 1;
      // Add size of sessionId
      size += (getSessionId() != null ? getSessionId().length() : 0);

      return size;
   }

   @Override
   public String toString() {
      StringBuilder result = new StringBuilder();
      String NEW_LINE = System.getProperty("line.separator");

      result.append(this.getClass().getSimpleName() + " Object {" + NEW_LINE);
      result.append(" user: " + user + NEW_LINE);
      result.append(" newPassword: " + newPassword + NEW_LINE);
      result.append(" changed: " + changed + NEW_LINE);
      result.append(" sessionId: " + sessionId + NEW_LINE);

      result.append("} ");

      return result.toString();
   }

   /**
    * The hashCode method returns this object's hashCode.
    */
   @Override
   public int hashCode() {
      final int prime = 31;
      int result = 1;
      result = prime * result
         + ((String) user).hashCode();
      result = prime * result
         + ((String) newPassword).hashCode();
      result = prime * result
         + ((Boolean) changed).hashCode();
      result = prime * result
         + ((String) sessionId).hashCode();
      return result;
   }

   /**
    * The equals method checks for equality. 
    */
   public boolean equals(Object obj) {
      if (obj == this) return true;
      if (obj == null) return false;
      if (getClass() != obj.getClass()) return false;

      ResponseChangePassword responseChangePassword = (ResponseChangePassword) obj;
      if (!responseChangePassword.getUser().equals(this.getUser())) {
         return false;
      }

      if (responseChangePassword.getNewPassword() == null && this.getNewPassword() != null) {
         return false;
      }
      else if (responseChangePassword.getNewPassword() != null && this.getNewPassword() == null) {
         return false;
      }
      else if (responseChangePassword.getNewPassword() != null && 
      !responseChangePassword.getNewPassword().equals(this.getNewPassword())) {
         return false;
      }

      if (responseChangePassword.getChanged() != this.getChanged()) {
         return false;
      }

      if (!responseChangePassword.getSessionId().equals(this.getSessionId())) {
         return false;
      }

      return true;
   }
}
