/*
 * WARNING: This file was generated by BitByBitGenerator.xtend (see
 * generateEnumFile()). 
 * Do not edit.
 */
package com.viacron.greenball.app.bbb;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

public enum UserRoleEnum {
    CONTRACTOR(0, "Contractor"),
    CUSTOMER(1, "Customer"),
    DEFUNCT(2, "Defunct"),
    OWNER(3, "Owner"),
    DEVELOPER(4, "Developer"),
    SIGNUP(5, "SignUp"),
    SUPPORT(6, "Support"),
    TRAINING(7, "Training");

   private static final Map<Integer, UserRoleEnum> lookup = new HashMap<Integer, UserRoleEnum>();

   static {
      for (UserRoleEnum enumType : EnumSet.allOf(UserRoleEnum.class)) {
         lookup.put(enumType.getId(), enumType);
      }
   }

   private final int id;
   private final String value;

   UserRoleEnum(int id, String v) {
      this.id = id;
      this.value = v;
   }

   public int getId() {
      return this.id;
   }

   public String value() {
      return this.value;
   }

   public static UserRoleEnum fromValue(String v) {
      for (UserRoleEnum userRoleEnum : UserRoleEnum.values()) {
         if (userRoleEnum.value.equals(v)) {
               return userRoleEnum;
         }
      }
      throw new IllegalArgumentException(v);
   }

   public static UserRoleEnum toEnum(int id) {
      return lookup.get(id);
   }
}
