/*
* generated by Xtext
*/
package com.viacron.utils.bbb.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ByteByByteOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
