/*
 * WARNING: This file was generated by BitByBitGenerator.xtend (see
 * generateInitializationFile()). 
 * Do not edit.
 */
package com.viacron.greenball.app.bbb;
import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import com.viacron.utils.StringMessageBuffer.parser.AbstractAttribute;
import com.viacron.utils.StringMessageBuffer.parser.Element;
import com.viacron.utils.StringMessageBuffer.parser.KeyValuePair;

/**
 * The InitializeUpdateOrganizationList class initializes the element object with the UpdateOrganizationList object.
 *
 */
public class InitializeUpdateOrganizationList {
   private static Logger log4j = Logger.getLogger(InitializeUpdateOrganizationList.class);
   private String theErrorMsg;
   private Element element;
   private UpdateOrganizationList updateOrganizationList;

   /**
    * The InitializeUpdateOrganizationList class initializes the element object with the UpdateOrganizationList object.
    *
    * @param updateOrganizationList The object which will be used to initialize the element object.
    */
   public InitializeUpdateOrganizationList(UpdateOrganizationList updateOrganizationList) {
      this.updateOrganizationList = updateOrganizationList;

      this.element = new Element("UpdateOrganizationList");
   }

   /**
    * This method initializes the element.
    */
   public Element initialize() throws MissingAttributeException {
      final String METHOD = "initialize()";
      log4j.debug("Entered " + METHOD);

      log4j.debug("element.getName(): UpdateOrganizationList");

      if (updateOrganizationList.getOrganization() != null) {
         AbstractAttribute abstractAttribute = initializeOrganization(updateOrganizationList.getOrganization());
         element.getAbstractAttributes().add(abstractAttribute);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"organization\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }

      if (updateOrganizationList.getSessionId() != null) {
         AbstractAttribute abstractAttribute = initializeSessionId(updateOrganizationList.getSessionId());
         element.getAbstractAttributes().add(abstractAttribute);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"sessionId\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }


      log4j.debug("Leaving " + METHOD);
      return element;
   }

   /*
    * This method initializes the organization attribute.
    * Generated by initAttributeMethods()
    */
   private AbstractAttribute initializeOrganization(OrganizationSubType organization)
             throws MissingAttributeException {
      AbstractAttribute abstractAttribute = new AbstractAttribute();
      if (organization != null) {
         InitializeOrganizationSubType initializeOrganizationSubType = new InitializeOrganizationSubType(organization);
         Element organizationElement = initializeOrganizationSubType.initialize("organization");
         abstractAttribute.getElements().add(organizationElement);
      }
   else {
      // Missing required attribute, generate an error message and throw an exception
      setErrorMsg("Error packing object. The attribute \"organization\" is required, but no value was provided.");
      log4j.error(getErrorMsg());
      throw new MissingAttributeException(getErrorMsg());
   }
      return abstractAttribute;
   }

   /*
    * This method initializes the sessionId attribute.
    * Generated by initAttributeMethods()
    */
   private AbstractAttribute initializeSessionId(String sessionId)
         throws MissingAttributeException {
      AbstractAttribute abstractAttribute = new AbstractAttribute();
      // Entered initAbstractAttributeValue()
      // Entered initAttributeValue()
      if (sessionId != null) {
         log4j.debug("Creating new KeyValuePair: sessionId");
         KeyValuePair kvp = new KeyValuePair("sessionId", "<STRING_BEGIN>" + sessionId + "<STRING_END>");
         abstractAttribute.getKeyValuePairs().add(kvp);
      }
      else {
         // Missing required attribute, generate an error message and throw an exception
         setErrorMsg("Error packing object. The attribute \"sessionId\" is required, but no value was provided.");
         log4j.error(getErrorMsg());
         throw new MissingAttributeException(getErrorMsg());
      }

      // Leaving initAttributeValue()
      // Leaving initAbstractAttributeValue()
      return abstractAttribute;
   }

   /**
   * This method returns the error message or null if no error occurred.
   */
   public String getErrorMsg() {
      return theErrorMsg;
   }

   private void setErrorMsg(String errorMsg) {
      theErrorMsg = errorMsg;
   }

}
