/*
 * WARNING: This file was generated by BitByBitGenerator.xtend (see
 * generateInstantiationFile()). 
 * Do not edit.
 */
package com.viacron.greenball.app.bbb;
import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import com.viacron.utils.StringMessageBuffer.parser.AbstractAttribute;
import com.viacron.utils.StringMessageBuffer.parser.Element;
import com.viacron.utils.StringMessageBuffer.parser.KeyValuePair;

public class InstantiateErrorMessage {
   private static Logger log4j = Logger.getLogger(InstantiateErrorMessage.class);

   /*
    * The isUpdated flags. If an attribute is required by the grammar then a value
    * must be provided, and the isUpdated flag will be set when the value is
    * obtained during unpacking. After the object is constructed during unpacking, 
    * validation will be performed to make sure a value was provided for all attributes
    * that are not optional. 
    * See buildFlags() in JBitByBitGenerator.java.
    */
   private boolean isIdUpdated = false;
   private boolean isMsgUpdated = false;

   private Element element;
   private ErrorMessage errorMessage;

   /**
    * The InstantiateErrorMessage class instantiates the ErrorMessage object.
    *
    * @param element The root element returned by the parser after parsing the string
    *                representing the ErrorMessage.
    */
   public InstantiateErrorMessage(Element element) {
      this.element = element;   
      this.errorMessage = new ErrorMessage();
   }

   /**
    * This method instantiates the ErrorMessage.
    *
    * @return The ErrorMessage.
    */
   public ErrorMessage instantiate() {
      final String METHOD = "instantiate()";
      log4j.debug("Entered " + METHOD);

      log4j.debug("ErrorMessage: " + element.getName());
      log4j.debug("# of attributes: " + element.getAbstractAttributes().size());

      instantiateErrorMessageAttributes(element);

      for (AbstractAttribute abstractAttribute : element
            .getAbstractAttributes()) {
         for (Element e : abstractAttribute.getElements()) {
            log4j.debug("element name: " + e.getName());
      instantiateErrorMessageSubTypeRefs(e);
      }
      }

      log4j.debug("Leaving " + METHOD);
      return errorMessage;
      }

      /*
       * This method instantiates the ErrorMessage attributes.
       * 
       * @param Element element
       */
      private void instantiateErrorMessageAttributes(Element element) {
      final String METHOD = "instantiateErrorMessageAttributes()";
      log4j.debug("Entered " + METHOD);

      log4j.debug("element name: " + element.getName());
      for (AbstractAttribute attr : element.getAbstractAttributes()) {
         for (KeyValuePair kvp : attr.getKeyValuePairs()) {
            log4j.debug("key: " + kvp.getKey());
            log4j.debug("value: " + kvp.getValue());
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("id")) {
               log4j.debug("setting value of \"id\" to: " + kvp.getValue());
               this.isIdUpdated = true;
               errorMessage.setId(Integer.parseInt(kvp.getValue()));
            }
            // Leaving instantiateMsgAttribute()
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("msg")) {
               log4j.debug("setting value of \"msg\" to: " + kvp.getValue());
               this.isMsgUpdated = true;
               errorMessage.setMsg(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("details")) {
               log4j.debug("setting value of \"details\" to: " + kvp.getValue());
               errorMessage.setDetails(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
            // Entered instantiateMsgAttribute()
            if (kvp.getKey().equals("sessionId")) {
               log4j.debug("setting value of \"sessionId\" to: " + kvp.getValue());
               errorMessage.setSessionId(kvp.getValue());
            }
            // Leaving instantiateMsgAttribute()
         }
      }

      log4j.debug("Leaving " + METHOD);
   }

   /*
    * This method instantiates the ErrorMessage SubType references.
    * 
    * @param Element element
    */
   private void instantiateErrorMessageSubTypeRefs(Element element) {
      final String METHOD = "instantiateErrorMessageSubTypeRefs()";
      log4j.debug("Entered " + METHOD);


      log4j.debug("Leaving " + METHOD);
   }


   /**
    * The validate method checks that a value was provided for all required 
    * attributes.
    *
    * @return The error message or null if no error occurred.
    */
   protected String validate() {
      final String METHOD = "validate()";
      log4j.debug("Entered " + METHOD);

      String result = null;

      // Entered buildValidationMethod()
      if (!this.isIdUpdated) {
         String msg = "Id is required, but no value was provided.";
         if (result == null) {
            result = msg;
         }
      }

      if (!this.isMsgUpdated) {
         String msg = "Msg is required, but no value was provided.";
         if (result == null) {
            result = msg;
         }
         else {
            result = result.concat("\n" + msg);
         }
      }


      if (result != null) {
         log4j.debug("result: " + result);
      }

      log4j.debug("Leaving " + METHOD);
      return result;
   }
}
